/*
 * Copyright 1999–2025 ViaOA (info@viaoa.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.viaoa.guid;

import java.util.concurrent.atomic.AtomicLong;

import com.viaoa.converter.OAConv;
import com.viaoa.lang.OAInteger;
import com.viaoa.lang.OAString;
import com.viaoa.net.OANetwork;

/**
 * Generates a 64-bit GUID whose high-order bits encode information about the
 * machine and environment, and whose low-order bits form a sequential counter.
 * <p>
 *
 * The GUID structure is:
 * <ul>
 *   <li><b>1 bit</b>: sign bit, always 0 to ensure a non-negative value</li>
 *   <li><b>8 bits</b>: the fourth octet of the machine's IPv4 address</li>
 *   <li><b>N bits</b>: optional extra feature bits based on the supplied
 *       boolean array</li>
 *   <li><b>remaining bits</b>: available for a monotonically increasing
 *       counter</li>
 * </ul>
 *
 * The number of bits required for the counter is specified by the
 * <code>bitsNeeded</code> constructor argument. During initialization the class
 * computes the maximum usable counter range, constructs a starting identifier,
 * and creates an {@link java.util.concurrent.atomic.AtomicLong} for generating
 * the sequence. <p>
 *
 * GUID generation is thread-safe. The {@link #getNextId()} method lazily
 * initializes the bit layout on first use, then returns successive values
 * within the allocated bit range. The high-order bits remain constant for the
 * lifetime of the instance. <p>
 *
 * This class is useful for distributed systems where independent servers must
 * generate unique, non-colliding identifiers without coordination while still
 * embedding node information in the identifier.
 */
public class OAGuidIp4 {
	
	/**
	 * Optional feature-bit flags used to augment the high-order portion of the GUID.
	 * <p>
	 * Each {@code true} value in this array causes an additional bit to be set
	 * in the identifier during initialization, allowing extra environment or
	 * feature-specific information to be encoded into the GUID.
	 */
	private final boolean[] bAddExtraBits;
	
	/**
	 * The number of bits required for the sequential counter portion of the GUID.
	 * <p>
	 * This value is used during initialization to determine how many of the
	 * remaining low-order bits are allocated for the monotonic counter.
	 */
	private final int bitsNeeded;
	
	/**
	 * Atomic counter used to generate successive GUID values.
	 * <p>
	 * The counter is initialized during {@link #init()} and incremented
	 * atomically to ensure thread-safe, monotonically increasing identifiers.
	 */
	private volatile AtomicLong nextId;
	
	/**
	 * The total number of high-order bits consumed by fixed identifier components.
	 * <p>
	 * This includes the sign bit, IPv4 octet bits, and any extra feature bits.
	 */
	private int bitsUsed;
	
	/**
	 * The number of remaining bits available for the sequential counter.
	 * <p>
	 * This value is computed during initialization based on {@link #bitsNeeded}
	 * and the number of fixed high-order bits used.
	 */
	private int bitsAvailable;
	
	/**
	 * The first usable identifier value generated by this instance.
	 * <p>
	 * This value represents the base identifier after all high-order bits
	 * have been set and before counter incrementation begins.
	 */
	private long startId;
	
	/**
	 * The maximum identifier value that can be generated by this instance.
	 * <p>
	 * This value reflects the upper bound imposed by the allocated counter bits
	 * and is computed during initialization.
	 */
	private long maxValue;
	
	/**
	 * Indicates whether this GUID generator has been initialized.
	 * <p>
	 * Initialization is performed lazily on first access to ensure that
	 * network and bit-layout information is resolved only when needed.
	 */
	private volatile boolean bInit;

	/**
	 * Creates a new IPv4-based GUID generator.
	 * <p>
	 * The generated identifiers embed the fourth octet of the local IPv4 address,
	 * optional feature bits, and a sequential counter within a 64-bit value.
	 *
	 * @param bitsNeeded the number of bits required for the sequential counter
	 * @param bAddExtraBits optional flags indicating which extra feature bits to set
	 */
	public OAGuidIp4(int bitsNeeded, boolean... bAddExtraBits) {
		this.bitsNeeded = bitsNeeded;
		this.bAddExtraBits = bAddExtraBits;
	}

	/**
	 * Returns the next available GUID value.
	 * <p>
	 * The generator is lazily initialized on first use. Each invocation returns
	 * a unique, monotonically increasing identifier within the allocated bit range.
	 *
	 * @return the next generated GUID value
	 */
	public long getNextId() {
		if (!bInit) {
			init();
		}
		long id = nextId.getAndIncrement();
		return id;
	}

	/**
	 * Initializes the GUID generator by computing the bit layout and counter range.
	 * <p>
	 * This method derives the high-order identifier bits from the local machine's
	 * IPv4 address and any configured feature bits, then allocates the remaining
	 * low-order bits for the sequential counter.
	 * <p>
	 * Initialization is performed lazily and is safe to call multiple times;
	 * subsequent calls return immediately once initialization is complete.
	 */
	public synchronized void init() {
		if (bInit) {
			return;
		}

		String ip = OANetwork.getIPAddress();
		String ips = OAString.field(ip, ".", 4);
		long ipx = OAConv.toLong(ips);

		// shift 8 bit IP to left, but not using negative bit
		long id = ipx << (64 - 9);

		for (int i = 0; i < bAddExtraBits.length; i++) {
			if (bAddExtraBits[i]) {
				int x = (64 - (10 + i));
				id |= (1L << x);
			}
		}

		// shift right for unneeded bits
		bitsUsed = 1 + 8 + bAddExtraBits.length;
		bitsAvailable = 64 - bitsUsed;

		if (bitsAvailable > bitsNeeded) {
			int shift = bitsAvailable - bitsNeeded;
			id = id >>> shift;
			bitsAvailable = bitsNeeded;
		}

		long maxValue = id + ((long) Math.pow(2, bitsAvailable)) - 1;

		this.startId = id + 1;
		nextId = new AtomicLong(this.startId);

		maxValue = 1;
		for (int i = 0; i < bitsAvailable; i++) {
			maxValue *= 2;
		}

		maxValue |= nextId.longValue();
		bInit = true;
	}

	/**
	 * Returns the total number of bits consumed by fixed identifier components.
	 * <p>
	 * This includes the sign bit, IPv4 octet bits, and any configured feature bits.
	 *
	 * @return the number of high-order bits used
	 */
	public int getBitsUsed() {
		init();
		return bitsUsed;
	}

	/**
	 * Returns the number of bits available for the sequential counter.
	 * <p>
	 * This value reflects the remaining low-order bits after fixed identifier
	 * components have been allocated.
	 *
	 * @return the number of bits available for counter values
	 */
	public int getBitsAvailable() {
		init();
		return bitsAvailable;
	}

	/**
	 * Returns the maximum identifier value that can be generated.
	 * <p>
	 * This represents the upper bound imposed by the allocated counter bits
	 * and is computed during initialization.
	 *
	 * @return the maximum possible GUID value
	 */
	public long getMaxValue() {
		init();
		return maxValue;
	}

}
